#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
count=1
while [ $count -lt 10 ]
do 
if [ $count -eq 9 ]
then
echo -e "Best school\nHi"
fi
echo "Best School"
((count++))
done
